name: api ci cd

on:
  push:
    branches:
      - main


jobs:
  NotTodo:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Repository에 올린 파일들 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: 마리아 DB 설정
        uses: getong/mariadb-action@v1.1
        with:
          host port: 3306
          mysql database: 'nottodo'
          mysql user: 'todo'
          mysql password: ${{ secrets.DB_PASSWORD }}

      - name: application properties 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: gradle 권한 추가
        run: chmod +x gradlew

      - name: gradle 빌드
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: project.jar
          target: /root/NotToDo-API

      - name: SSH로 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            envs: APPLICATION_PROPERTIES
            script_stop: true
            script: |
              rm -rf /root/NotToDo-API/target
              mkdir /root/NotToDo-API/target
              mv /root/NotToDo-API/target/tobe/project.jar /root/NotToDo-API/target
              cd /root/NotToDo-API/target
              sudo fuser -k -n tcp 8080 || true
              nohup java -jar project.jar > ./output.log 2>&1 &
              rm -rf /root/NotToDo-API/target/tobe

