name: api ci cd

on:
  push:
    branches:
      - main


jobs:
  NotTodo:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.4.10
        options: >-
          --name mariadb
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: nottodo
          MYSQL_USER: todo
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306

    steps:
      - name: GitHub Repository에 올린 파일들 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'


      - name: application properties 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties


      - name: MariaDB 권한 설정
        run: |
          container_id=$(docker ps -qf "ancestor=mariadb:10.4.10")
          docker exec $container_id mysql -uroot -p1234 -e "GRANT ALL PRIVILEGES ON nottodo.* TO 'todo'@'%' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}'; FLUSH PRIVILEGES;"
      - name: gradle 권한 추가
        run: chmod +x gradlew

      - name: gradle 빌드
        env:
          SPRING_JPA_HIBERNATE_DDL_AUTO: update
        run: ./gradlew clean build --stacktrace --info

      - name: 빌드된 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: project.jar
          target: /root/NotToDo-API/tobe

      - name: SSH로 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: APPLICATION_PROPERTIES
          script_stop: true
          script: |
            sudo systemctl restart mariadb
            chmod +x setup.sh
            ./setup.sh
            rm -rf /root/NotToDo-API/target
            mkdir /root/NotToDo-API/target
            mv /root/NotToDo-API/tobe/project.jar /root/NotToDo-API/target
            cd /root/NotToDo-API/target
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar > ./output.log 2>&1 &
            rm -rf /root/NotToDo-API/tobe
